### ISSUE TITLE
Target offline app instead of cloud service

### ISSUE THREAD

**Issue by mixmastrbrock** [bitfocus/companion-module-stagetimerio-api#4]
With the beta launch of their offline server, is there a way to point the API calls to a local server instead of the cloud API?

**Comment by painteau** [comment]
I plus plus that ! It looks like its just a change of  url only

`For example, instead of using the URL https://api.stagetimer.io/v0/room/YOUR_ROOM_ID/start as you would with the web version, you will use https://127.0.0.1:3000/api/v0/room/YOUR_ROOM_ID/start, replacing 127.0.0.1 with the IP address and 3000 with the port number chosen when starting the offline version.`

**Comment by lhermann** [comment]
Yes. The offline version comes with the same API, but the URL is now the IP address of you computer (or 127.0.0.1)

We're planing to update the Companion module in the coming month, including a way to point it at another URL / offline version.

**Comment by shermanp** [comment]
Seems like this is still an issue using V3.1.2.

Notice that I can not save a offline API URL with .../api/v0/ but can save it with .../api/v1/ but module reports Connection Failure.

**Comment by lhermann** [comment]
In the Stagetimer Offline Version v2.9.3 the API popup looks like this:
<img width="300" alt="image" src="https://github.com/bitfocus/companion-module-stagetimerio-api/assets/2800117/3faacd3d-0c41-467c-8336-b6dc8ec249b9">

The defaults when adding a stagetimer connection in Companion v3.1.2 look like this:
<img width="300" alt="image" src="https://github.com/bitfocus/companion-module-stagetimerio-api/assets/2800117/cade3acd-33af-499b-933b-d1b729d23e20">

The Companion v3+ module only works with the v1 API from Stagetimer. The v1 API offers a web socket connection which the companion module uses to show feedback states.
