### ISSUE TITLE
Companion connection based on variables, output variables, and Feedback

### ISSUE THREAD

**Issue by RayHAz** [bitfocus/companion-module-stagetimerio-api#5]
I have a Companion page dedicated to StageTimer.  I'd like to be able to switch between rooms easily without having to manually enter Room ID and API Key.  I can store these items locally and push them over to a Companion variable with their API.  Is there a way to have the Companion connection work off of a variable?  (I know that's a Companion question more than a question about the Stagetimer module - sorry.)

Or is there another easy way to change the connection settings I'm missing?

Would like for the Stagetimer variables to include Room Name and possibly Room ID (so I can confirm visually that I've got the right Room set up).

Would also be great to have Feedback settings on whether a timer is running or paused.

Sorry I'm not much help on programming (good skills, but old-school stuff), but I can help with testing and maybe some "light coding" or code review.
![image](https://user-images.githubusercontent.com/10144077/224106939-16bad867-f5a7-4f09-8bc2-4af10850f415.png)

**Comment by kgfox1** [comment]
Hi Ray,

It's not elegant but until they add more API triggers here is my suggestion:
- Since each Stagetimer Room is a specific Companion connection, create a Companion Page for each room.
- Add a Next Room button that increases the Page Count by 1
- Add a Prev Room button that decreases the Page Count by 1
- Add a button that has just text in it that has the Room number for each page (i.e. Companion Page 3 has Room XLTJ2B or just Current Room 1)

I have just started using Stagetimer and have not needed more than 4 timers in 1 room.  So my companion page is pretty simple.

**Comment by dnmeid** [comment]
I'm not into the stagetimer module but as far as it concerns Companion, dynamic connection endpoints are completely possible. The fields in the configuration are intended for static data only, but if a module developer wants to have a dynamic connection, he can offer actions for changing the endpoint.
This won't make sense for most of the modules and the problems you may get are usually bigger than the problems you solve, that is why it usually isn't offered.

**Comment by RayHAz** [comment]
Excellent!  Thanks @lhermann.  I'll check it out...

**Comment by lhermann** [comment]
FYI: You can add multiple connection of the same module. So you can connect two stagetimer integrations targeting different rooms to control multiple rooms from a single streamdeck device.

<img width="601" alt="image" src="https://github.com/bitfocus/companion-module-stagetimerio-api/assets/2800117/b3ca4d3b-7967-4964-92ce-a1b7e8be05d3">
